DROP TABLE IF EXISTS PARKING;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS PARKING (
    PARKING_CODE INT(4) NOT NULL UNIQUE,
    PARKING_STATUS BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
	USER_NO INT(4) AUTO_INCREMENT,
	USER_NAME VARCHAR(40) NOT NULL UNIQUE,
	USER_PASS VARCHAR(40) NOT NULL,
	PRIMARY KEY(USER_NO)
);

INSERT INTO USERS(USER_NAME, USER_PASS) VALUES("root", "root");
